### ISSUE TITLE
generator: Add better optionparsing

### ISSUE THREAD

**Issue by NobbZ** [exercism/erlang-tests-generator#4]
The new optionparsing should at least have the following flags/commands:

* [ ] `help`: explains how to use the script, also optional is to extend it with indepth documentation of each other command.
* [ ] `check`: checks all/given exercises if they would generate files that are different than the current ones
* [ ] `diff`: (*optional*) print a unified diff for all/given exercises
* [X] (#209) `generate`: (re)-generate all/given exercises
* [X] (#209) `--path`: specifies the path to the git base folder
* [X] (#209) `--spec-path`: Path to the spcification repository. Usually derived from erlang repository path. Defaults to `${path}/canonical_data/exercises`
* [X] (#209) `--out-path`: Path to write generated files to. Usually derived from erlang repository path. `${path}/exercises`
